input_display:


<input_display>:
    BoxLayout:
        orientation: "vertical"
        size: root.width,root.height     
        TextInput:
            id:input_box 
            text: "0"
            multiline: False  
            halign:"right"  #honrizontal align
            font_size:45
            color: 1,1,1,1
        Gridlayout:
            cols : 4
            rows : 5
            
            size_hint : 1, 6
            

            #### Row1 ####
            Button:
                text:"AC"
                font_size : 35
                on_press : root.clear_num()

            Button:
                text:"+/-"
                font_size : 35
                on_press : root.pos_neg()
            Button:
                text:"DEL" 
                font_size : 35
                on_press : root.delete()
            
            Button:
                text:"÷"
                font_size : 35
                background_color:(0/255, 150/255, 170/255,1)
                on_press : root.value("÷")

            #### Row2 ####
            Button:
                text:"7"
                font_size : 35
                on_press : root.value(7)
            Button:
                text:"8"
                font_size : 35
                on_press : root.value(8)
            Button:
                text:"9"
                font_size : 35
                on_press : root.value(9)
            Button:
                text:"x"
                font_size : 35
                background_color:(0/255, 150/255, 170/255,1)
                on_press : root.value("x")


            #### Row3 ####
            Button:
                text:"4"
                font_size : 35
                on_press : root.value(4)
            Button:
                text:"5"
                font_size : 35
                on_press : root.value(5)
            Button:
                text:"6"
                font_size : 35
                on_press : root.value(6)
            Button:
                text:"-"
                font_size : 35
                background_color:(0/255, 150/255, 170/255,1)
                on_press : root.value("-")

            
            #### Row4 ####
            Button:
                text:"1"
                font_size : 35
                on_press : root.value(1)
            Button:
                text:"2"
                font_size : 35
                on_press : root.value(2)
            Button:
                text:"3"
                font_size : 35
                on_press : root.value(3)
            Button:
                text:"+"
                font_size : 35
                background_color:(0/255, 150/255, 170/255,1)
                on_press : root.value("+")


            #### Row5 ####
            Button:
                text:"%"
                font_size : 35
                on_press : root.value("%")
            Button:
                text:"0"
                font_size : 35
                on_press : root.value(0)
            Button:
                text:"."
                font_size : 35
                on_press : root.value(".")
            Button:
                text:"="
                font_size : 35
                background_color:(0/255, 150/255, 170/255,1)
                on_press : root.result() 
                
        
       

   



    
    
    
   
